### PR TITLE
Switch pointers to official bootstrap package

### PR DESCRIPTION
**Pull request by splendido**

### CODE REVIEW

**Comment by PeppeL-G** [comment]
Thanks! However, now when there's an official meteor package for bootstrap, should this package include that one automatically? Sounds like a good idea to me, but I just want to check with someone (you) that I'm doing something stupid.

**Comment by splendido** [comment]
Yeah, it's true there's an official package but it's the compiled CSS version.
For example if you'd like to customize your style or apply some theming you'd probably choose [nemo64:bootstrap](https://atmospherejs.com/nemo64/bootstrap)...

So, I'd say your package is fine as it is now, without dependencies.

Does this makes sense?

**Comment by PeppeL-G** [comment]
Yea, I'm totally buying that. I thought ~99% would be using the `twbs:bootstrap` package instead of one of the alternatives, but it seems like I was quite wrong. Let's stick to what we've got. 

Thanks for the input!

**Comment by Maxhodges** [comment]
+1 https://atmospherejs.com/nemo64/bootstrap
stellar way of adding bootstrap to meteor

**Pull request merged**
