### PR TITLE
Modal options argument.

### PR DESCRIPTION
**Pull request by greyarch**
Allow for passing options parameter to the show method, will be used on modal creation.

### CODE REVIEW

**Comment by PeppeL-G** [comment]
Sorry for the late respond.

I still see no use case for this, but since people keep asking for it, let's add it.

Thanks!

**Comment by greyarch** [comment]
Thanks, dude. My personal use case is to be able to add the options to prevent the modal from closing when the user (accidentally) clicks outside of it. I tried to explain in the readme. I imagine other people would like to use it this way too.

**Comment by PeppeL-G** [comment]
Yea, but isn't it better to instead use the `data-`attributes to add that functionality? Only write it once in your template instead of each time you want to open the modal.

**Comment by greyarch** [comment]
Doesn't this only work if you put these attribs on the the triggering element, the one with the data-toggle attribute. At least that's how I understand it.

If you want to have more control (maybe some logic for what options to use) when opening the modal you have to do it programmatically in which case you need to be able to put the options on the show call.

**Comment by PeppeL-G** [comment]
I'm quite sure you can put the `data-` attributes directly on the root element of the modal, that's what I've been doing (I think, I haven't been using this for a year now, I may not remember correctly).

Yea, that's the only use case I've been able to come up with as well, but since it (at least to me) seems weird to customize such a behavior, I've been rejecting the options-parameter until someone actually had a true need for it. But what's done is done, let's see how things evolve from here :)

**Pull request merged**
